export const ICONS = {
  myComputer: "/icons/my_computer.png",
  recycle: "/icons/recycle.png",
  notepad: "/icons/notepad.png",
  paint: "/icons/paint.png",
  calc: "/icons/calc.png",
  ie: "/icons/ie.png",
  explorer: "/icons/explorer.png",
  fileShare: "/icons/file_share.png",
  chat: "/icons/chat.png",
  controlPanel: "/icons/control_panel.png",
  minesweeper: "/icons/minesweeper.png",
  about: "/icons/about.png",
  run: "/icons/run.png",
  hardDrive: "/icons/hard_drive.png",
  floppy: "/icons/floppy.png",
  cd: "/icons/cd.png",
  folderClosed: "/icons/folder_closed.png",
  folderOpen: "/icons/folder_open.png",
  fileWindows: "/icons/file_windows.png",
} as const;

// Fallback emoji for when image fails to load
export const ICON_FALLBACK: Record<string, string> = {
  myComputer: "💻",
  recycle: "🗑️",
  notepad: "📝",
  paint: "🎨",
  calc: "🧮",
  ie: "🌐",
  explorer: "📂",
  fileShare: "📁",
  chat: "💬",
  controlPanel: "⚙️",
  minesweeper: "💣",
  about: "ℹ️",
  run: "▶️",
  hardDrive: "💾",
  floppy: "💿",
  cd: "📀",
  folderClosed: "📁",
  folderOpen: "📂",
  fileWindows: "📄",
};
